name: linkwarden-telegram-bot
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-linkwarden-bot
    networks:
      - linkwarden-internal
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - LINKWARDEN_API_URL=${LINKWARDEN_API_URL}
      - LINKWARDEN_API_KEY=${LINKWARDEN_API_KEY}
      - LINKWARDEN_COLLECTION_ID=${LINKWARDEN_COLLECTION_ID}
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped

networks:
  linkwarden-internal:
