name: linkwarden
services:

  linkwarden-telegram-bot:
    container_name: telegram-linkwarden-bot
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/orguetta/linkwarden-telegram-bot:latest
    networks:
      - internal
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - LINKWARDEN_API_URL=${LINKWARDEN_API_URL}
      - LINKWARDEN_API_KEY=${LINKWARDEN_API_KEY}
      - LINKWARDEN_COLLECTION_ID=${LINKWARDEN_COLLECTION_ID}
    restart: unless-stopped

networks:
  internal:
